filebeat.inputs:
- type: docker
  containers:
    path: "/var/lib/docker/containers"
    ids:
      - "*"
  processors:
    - add_docker_metadata: ~
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST:elasticsearch:9200}"]

